# Generated by Django 5.0.3 on 2024-10-12 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='descrição')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
            ],
            options={
                'verbose_name': 'notícia',
                'verbose_name_plural': 'notícias',
                'db_table': 'news',
                'managed': True,
            },
        ),
    ]
