# Generated by Django 5.0.3 on 2024-07-30 19:53

import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramyoutubedownload',
            name='TelegramChatMessage_update_id',
            field=models.ForeignKey(db_column='TelegramChatMessage_update_id', on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramchatmessage', verbose_name='chat message'),
        ),
        migrations.AlterField(
            model_name='telegramyoutubedownload',
            name='file_path',
            field=models.FilePathField(max_length=200, path=pathlib.PureWindowsPath('C:/Users/tiago/Desktop/Repositorio/Github/WandecleideSE/src/temp/youtube'), recursive=True, verbose_name='file path'),
        ),
    ]
