# Generated by Django 5.0.3 on 2024-10-12 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_telegramyoutubedownload_telegramchatmessage_update_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='update_id',
            field=models.PositiveBigIntegerField(db_index=True, help_text="update's unique identifier, allows you to ignore repeated updates or to restore the correct update sequence", primary_key=True, serialize=False, verbose_name='telegram update ID'),
        ),
        migrations.AlterField(
            model_name='telegramyoutubedownload',
            name='TelegramChatMessage_update_id',
            field=models.ForeignKey(db_column='TelegramChatMessage_update_id', on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramchatmessage', verbose_name='telegram update ID'),
        ),
        migrations.AlterField(
            model_name='telegramyoutubedownload',
            name='content_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'audio/mpeg')], verbose_name='content type'),
        ),
    ]
